//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalLocation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalLocation() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.GlobalLocation", typeof(GlobalLocation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bird.
        /// </summary>
        internal static string Bird {
            get {
                return ResourceManager.GetString("Bird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tweet Tweet!.
        /// </summary>
        internal static string BirdSound {
            get {
                return ResourceManager.GetString("BirdSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loyalty.
        /// </summary>
        internal static string BlueMeaning {
            get {
                return ResourceManager.GetString("BlueMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Im flying!.
        /// </summary>
        internal static string FlyPhrase {
            get {
                return ResourceManager.GetString("FlyPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hope.
        /// </summary>
        internal static string GreenMeaning {
            get {
                return ResourceManager.GetString("GreenMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grr!.
        /// </summary>
        internal static string MamalSound {
            get {
                return ResourceManager.GetString("MamalSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Love.
        /// </summary>
        internal static string RedMeaning {
            get {
                return ResourceManager.GetString("RedMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Im running!.
        /// </summary>
        internal static string RunPhrase {
            get {
                return ResourceManager.GetString("RunPhrase", resourceCulture);
            }
        }
    }
}
